name: openweathermap
description: OpenWeatherMap API Wrapper 
version: 0.0.3
homepage: https://github.com/ale183/openweathermap

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
